"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# =============================================================================
# ENVIRONMENT LOADING
# =============================================================================

# Determine environment type
is_docker = os.environ.get("IS_DOCKER", "false").lower() == "true"
base_dir = Path(__file__).resolve().parent.parent  # backend directory
root_dir = base_dir.parent  # project root directory

# Optimized environment loading - учитываем среду выполнения
# Следуем архитектуре ENV_SETUP.md: base → secrets → (local|docker) → service-specific
env_files = [
    root_dir / "env-config" / ".env.base",      # 1. Базовые переменные
    root_dir / "env-config" / ".env.secrets",   # 2. Секреты
]

# Добавляем файл среды в зависимости от IS_DOCKER
if is_docker:
    env_files.append(root_dir / "env-config" / ".env.docker")  # 3. Docker переопределения
else:
    env_files.append(root_dir / "env-config" / ".env.local")   # 3. Локальные переопределения

env_files.append(base_dir / ".env")  # 4. Backend-специфичные

# Загружаем все файлы по порядку (файлы сами определяют среду)
for env_file in env_files:
    if env_file.exists():
        load_dotenv(env_file, override=True)

# =============================================================================
# CORE DJANGO SETTINGS
# =============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-fallback-key-for-development")

# =============================================================================
# МИНИМАЛЬНЫЕ НАСТРОЙКИ ДЛЯ ЗАПУСКА
# =============================================================================

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")
print(f"SETTINGS: DEBUG before extra_config = {DEBUG}")
print(f"SETTINGS: DEBUG env var = {os.environ.get('DEBUG', 'NOT_SET')}")

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '*']

# Import all modular configurations early to avoid AppRegistryNotReady errors
from .extra_config import *  # noqa

# All other settings are imported from extra_config above

print(f"🔧 SETTINGS: DEBUG ПОСЛЕ импорта extra_config = {DEBUG}")
print(f"🔧 SETTINGS: ALLOWED_HOSTS = {ALLOWED_HOSTS}")
