# Generated by Django 5.2.4 on 2025-08-18 17:08

import core.validators.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profilemodel_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL of generated AI avatar",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to="avatars/",
                validators=[core.validators.file_validators.validate_avatar_file],
            ),
        ),
    ]
