# Generated by Django 5.2.4 on 2025-08-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profilemodel_avatar_url_alter_profilemodel_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilemodel",
            name="avatar_url",
        ),
    ]
