# Generated by Django 5.2.4 on 2025-08-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profilemodel_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="avatar_url",
            field=models.URLField(
                blank=True, help_text="URL for generated avatar images", null=True
            ),
        ),
    ]
