# Generated by Django 5.2.4 on 2025-08-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_profilemodel_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL for generated avatar images (local storage)",
                max_length=500,
                null=True,
            ),
        ),
    ]
