# Generated by Django 5.2.4 on 2025-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_profilemodel_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="avatar_url",
            field=models.TextField(
                blank=True,
                help_text="URL for generated avatar images (no length restrictions)",
                null=True,
            ),
        ),
    ]
