# Generated by Django 5.2.4 on 2025-10-09 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("ads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adinteraction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adviewdetail",
            name="interaction",
            field=models.OneToOneField(
                limit_choices_to={"interaction_type": "view"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_detail",
                to="ads.adinteraction",
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="account",
            field=models.ForeignKey(
                help_text="The account that owns this ad",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_ads",
                to="accounts.addsaccount",
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who moderated this ad (null for auto-moderation)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_ads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adviewmodel",
            name="ad",
            field=models.ForeignKey(
                help_text="Ad that was viewed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_views",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="adpromotionmodel",
            name="ad",
            field=models.ForeignKey(
                help_text="Ad that this promotion applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="adinteraction",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="addimagemodel",
            name="ad",
            field=models.ForeignKey(
                help_text="The advertisement this image belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="adcontact",
            name="car_ad",
            field=models.ForeignKey(
                help_text="Car advertisement this contact belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="mark",
            field=models.ForeignKey(
                db_column="mark_id",
                help_text="Mark of the car",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_ads",
                to="ads.carmarkmodel",
            ),
        ),
        migrations.AddField(
            model_name="carmetadatamodel",
            name="car_ad",
            field=models.OneToOneField(
                help_text="The car advertisement this metadata belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="mark",
            field=models.ForeignKey(
                db_column="make_id",
                help_text="The mark of this car model",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="ads.carmarkmodel",
            ),
        ),
        migrations.AddField(
            model_name="cargenerationmodel",
            name="model",
            field=models.ForeignKey(
                help_text="The car model this generation belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generations",
                to="ads.carmodel",
            ),
        ),
        migrations.AddField(
            model_name="carmodificationmodel",
            name="generation",
            field=models.ForeignKey(
                help_text="The car generation this modification belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifications",
                to="ads.cargenerationmodel",
            ),
        ),
        migrations.AddField(
            model_name="carpricehistorymodel",
            name="ad",
            field=models.ForeignKey(
                help_text="The car advertisement this price history belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="carspecificationmodel",
            name="car_ad",
            field=models.OneToOneField(
                help_text="The car advertisement these specifications belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specs",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="carspecificationmodel",
            name="color",
            field=models.ForeignKey(
                help_text="Color of the car",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_specs",
                to="ads.carcolormodel",
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="city",
            field=models.ForeignKey(
                db_column="city_id",
                help_text="City where the car is located",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_ads",
                to="ads.citymodel",
            ),
        ),
        migrations.AddField(
            model_name="favoritead",
            name="car_ad",
            field=models.ForeignKey(
                help_text="The car ad that was favorited",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="ads.carad",
            ),
        ),
        migrations.AddField(
            model_name="favoritead",
            name="user",
            field=models.ForeignKey(
                help_text="User who favorited this ad",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_ads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pageview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="regionmodel",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_region_name"
            ),
        ),
        migrations.AddField(
            model_name="citymodel",
            name="region",
            field=models.ForeignKey(
                help_text="The region this city belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="ads.regionmodel",
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="region",
            field=models.ForeignKey(
                db_column="region_id",
                help_text="Region where the car is located",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_ads",
                to="ads.regionmodel",
            ),
        ),
        migrations.AddField(
            model_name="savedsearchmodel",
            name="user",
            field=models.ForeignKey(
                help_text="User who created this saved search",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_searches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userbehaviorsummary",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_summary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carmarkmodel",
            name="vehicle_type",
            field=models.ForeignKey(
                help_text="Type of vehicle this mark belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="ads.vehicletypemodel",
                verbose_name="Vehicle Type",
            ),
        ),
        migrations.AddField(
            model_name="visitorsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_queries",
                to="ads.visitorsession",
            ),
        ),
        migrations.AddField(
            model_name="pageview",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_views",
                to="ads.visitorsession",
            ),
        ),
        migrations.AddField(
            model_name="adinteraction",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_interactions",
                to="ads.visitorsession",
            ),
        ),
        migrations.AddIndex(
            model_name="adcontact",
            index=models.Index(
                fields=["car_ad", "is_primary"], name="ad_contact_primary_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adcontact",
            index=models.Index(
                fields=["car_ad", "is_visible"], name="ad_contact_visible_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adcontact",
            index=models.Index(fields=["type"], name="ad_contact_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="adcontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("car_ad",),
                name="unique_primary_contact_per_ad",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carmodel",
            unique_together={("mark", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="cargenerationmodel",
            unique_together={("model", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="carmodificationmodel",
            unique_together={("generation", "name")},
        ),
        migrations.AddIndex(
            model_name="carpricehistorymodel",
            index=models.Index(
                fields=["ad", "date"], name="car_price_h_ad_id_3f1ad5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carpricehistorymodel",
            index=models.Index(fields=["date"], name="car_price_h_date_1bbda3_idx"),
        ),
        migrations.AddIndex(
            model_name="favoritead",
            index=models.Index(
                fields=["user", "favorited_at"], name="ads_favorit_user_id_649fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favoritead",
            index=models.Index(
                fields=["car_ad", "favorited_at"], name="ads_favorit_car_ad__12a880_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoritead",
            unique_together={("user", "car_ad")},
        ),
        migrations.AlterUniqueTogether(
            name="citymodel",
            unique_together={("name", "region")},
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["created_at"], name="car_ads_created_778c27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["seller_type"], name="car_ads_seller__bdc2c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["is_favorite"], name="car_ads_is_favo_cc0eea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["status", "created_at"], name="car_ads_status_66437e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["account", "status"], name="car_ads_account_c12faf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["mark", "status"], name="car_ads_mark_id_7ead6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["price", "currency"], name="car_ads_price_381e03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["region", "city"], name="car_ads_region__7f0af8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carmarkmodel",
            unique_together={("vehicle_type", "name")},
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["ip_address", "started_at"],
                name="ads_visitor_ip_addr_6a959b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["user", "started_at"], name="ads_visitor_user_id_df8a8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["started_at"], name="ads_visitor_started_0f08b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["query_text", "searched_at"],
                name="ads_search__query_t_0e9b42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["user", "searched_at"], name="ads_search__user_id_371485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session", "viewed_at"], name="ads_page_vi_session_06e784_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["user", "viewed_at"], name="ads_page_vi_user_id_110ea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_type", "viewed_at"], name="ads_page_vi_page_ty_03aa57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adinteraction",
            index=models.Index(
                fields=["ad", "interaction_type", "created_at"],
                name="ads_ad_inte_ad_id_bad903_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adinteraction",
            index=models.Index(
                fields=["user", "interaction_type", "created_at"],
                name="ads_ad_inte_user_id_897704_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adinteraction",
            index=models.Index(
                fields=["session", "created_at"], name="ads_ad_inte_session_eac344_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adinteraction",
            unique_together={("session", "ad", "interaction_type", "created_at")},
        ),
    ]
