# Generated by Django 5.2.4 on 2025-08-15 17:44

import core.validators.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_add_filter_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usd_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="USD to UAH exchange rate",
                        max_digits=10,
                    ),
                ),
                (
                    "eur_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="EUR to UAH exchange rate",
                        max_digits=10,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for these exchange rates", unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "db_table": "exchange_rates",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="carad",
            name="auto_moderation_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of auto-moderation attempts (max 3)"
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="manual_review_requested_at",
            field=models.DateTimeField(
                blank=True, help_text="When manual review was requested", null=True
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="needs_manual_review",
            field=models.BooleanField(
                default=False,
                help_text="Whether ad needs manual review after failed auto-moderation",
            ),
        ),
        migrations.AlterField(
            model_name="addimagemodel",
            name="image",
            field=models.ImageField(
                help_text="The image file",
                upload_to="ads/images/",
                validators=[core.validators.file_validators.validate_image_file],
            ),
        ),
    ]
