# Generated by Django 5.2.4 on 2025-08-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_add_metallic_pearlescent_to_colors"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="regionmodel",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="regionmodel",
            name="name",
            field=models.CharField(
                help_text="Name of the region in Ukrainian", max_length=100
            ),
        ),
        migrations.AddConstraint(
            model_name="carmarkmodel",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_car_mark_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="regionmodel",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_region_name"
            ),
        ),
    ]
