# Generated by Django 5.2.1 on 2025-08-21 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_change_address_to_onetoone'),
        ('ads', '0005_change_default_status_to_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Whether this ad is marked as favorite'),
        ),
        migrations.AddIndex(
            model_name='carad',
            index=models.Index(fields=['is_favorite'], name='car_ads_is_favo_cc0eea_idx'),
        ),
    ]
