# Generated by Django 5.2.4 on 2025-08-22 19:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_carad_is_favorite_carad_car_ads_is_favo_cc0eea_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Просмотр"),
                            ("phone_reveal", "Показ телефона"),
                            ("favorite_add", "Добавление в избранное"),
                            ("favorite_remove", "Удаление из избранного"),
                            ("contact_click", "Клик по контакту"),
                            ("photo_view", "Просмотр фото"),
                            ("share", "Поделиться"),
                            ("report", "Пожаловаться"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source_page", models.CharField(blank=True, max_length=100)),
                (
                    "position_in_list",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="ads.carad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ads_ad_interactions",
            },
        ),
        migrations.CreateModel(
            name="AdViewDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_duration", models.DurationField(blank=True, null=True)),
                ("time_to_first_scroll", models.DurationField(blank=True, null=True)),
                ("time_to_phone_reveal", models.DurationField(blank=True, null=True)),
                ("photos_viewed", models.PositiveIntegerField(default=0)),
                ("photos_viewed_list", models.JSONField(blank=True, default=list)),
                ("scroll_depth", models.FloatField(default=0.0)),
                ("clicks_on_elements", models.JSONField(blank=True, default=dict)),
                ("came_from", models.CharField(blank=True, max_length=200)),
                ("went_to", models.CharField(blank=True, max_length=200)),
                ("is_quality_view", models.BooleanField(default=False)),
                ("bounce", models.BooleanField(default=False)),
                (
                    "interaction",
                    models.OneToOneField(
                        limit_choices_to={"interaction_type": "view"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_detail",
                        to="ads.adinteraction",
                    ),
                ),
            ],
            options={
                "db_table": "ads_ad_view_details",
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("total_ad_views", models.PositiveIntegerField(default=0)),
                ("total_interactions", models.PositiveIntegerField(default=0)),
                ("avg_session_duration", models.DurationField(blank=True, null=True)),
                ("avg_pages_per_session", models.FloatField(default=0.0)),
                ("favorite_brands", models.JSONField(blank=True, default=list)),
                ("favorite_price_range", models.JSONField(blank=True, default=dict)),
                ("favorite_regions", models.JSONField(blank=True, default=list)),
                ("most_active_hours", models.JSONField(blank=True, default=list)),
                ("most_active_days", models.JSONField(blank=True, default=list)),
                ("device_preferences", models.JSONField(blank=True, default=dict)),
                ("phone_reveals_count", models.PositiveIntegerField(default=0)),
                ("favorites_added_count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_summary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ads_user_behavior_summaries",
            },
        ),
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("referrer", models.URLField(blank=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                        ],
                        max_length=50,
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_duration", models.DurationField(blank=True, null=True)),
                ("pages_viewed", models.PositiveIntegerField(default=0)),
                ("ads_viewed", models.PositiveIntegerField(default=0)),
                ("interactions_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ads_visitor_sessions",
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("filters_applied", models.JSONField(blank=True, default=dict)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("clicked_results", models.JSONField(blank=True, default=list)),
                (
                    "searched_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to="ads.visitorsession",
                    ),
                ),
            ],
            options={
                "db_table": "ads_search_queries",
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Главная"),
                            ("search", "Поиск"),
                            ("ad_detail", "Карточка объявления"),
                            ("user_profile", "Профиль пользователя"),
                            ("favorites", "Избранное"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                    ),
                ),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("viewed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("time_on_page", models.DurationField(blank=True, null=True)),
                ("scroll_depth", models.FloatField(default=0.0)),
                ("clicks_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="ads.visitorsession",
                    ),
                ),
            ],
            options={
                "db_table": "ads_page_views",
            },
        ),
        migrations.AddField(
            model_name="adinteraction",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_interactions",
                to="ads.visitorsession",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["ip_address", "started_at"],
                name="ads_visitor_ip_addr_6a959b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["user", "started_at"], name="ads_visitor_user_id_df8a8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["started_at"], name="ads_visitor_started_0f08b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["query_text", "searched_at"],
                name="ads_search__query_t_0e9b42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["user", "searched_at"], name="ads_search__user_id_371485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session", "viewed_at"], name="ads_page_vi_session_06e784_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["user", "viewed_at"], name="ads_page_vi_user_id_110ea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_type", "viewed_at"], name="ads_page_vi_page_ty_03aa57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adinteraction",
            index=models.Index(
                fields=["ad", "interaction_type", "created_at"],
                name="ads_ad_inte_ad_id_bad903_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adinteraction",
            index=models.Index(
                fields=["user", "interaction_type", "created_at"],
                name="ads_ad_inte_user_id_897704_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adinteraction",
            index=models.Index(
                fields=["session", "created_at"], name="ads_ad_inte_session_eac344_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adinteraction",
            unique_together={("session", "ad", "interaction_type", "created_at")},
        ),
    ]
