# Generated by Django 5.2.1 on 2025-09-01 22:54

import core.validators.file_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_create_analytics_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addimagemodel',
            name='image_url',
            field=models.TextField(blank=True, help_text='URL for generated images (no length restrictions)', null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text='When the ad was last moderated', null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='User who moderated this ad (null for auto-moderation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carad',
            name='moderation_reason',
            field=models.TextField(blank=True, help_text='Reason for moderation decision'),
        ),
        migrations.AlterField(
            model_name='addimagemodel',
            name='image',
            field=models.ImageField(blank=True, help_text='The image file', null=True, upload_to='ads/images/', validators=[core.validators.file_validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='carad',
            name='city',
            field=models.ForeignKey(db_column='city_id', help_text='City where the car is located', on_delete=django.db.models.deletion.PROTECT, related_name='car_ads', to='ads.citymodel'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='region',
            field=models.ForeignKey(db_column='region_id', help_text='Region where the car is located', on_delete=django.db.models.deletion.PROTECT, related_name='car_ads', to='ads.regionmodel'),
        ),
        migrations.CreateModel(
            name='AdContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('phone', '📞 Phone'), ('email', '📧 Email'), ('telegram', '📲 Telegram'), ('whatsapp', '💬 WhatsApp'), ('viber', '📡 Viber'), ('instagram', '📸 Instagram'), ('website', '🌐 Website')], help_text='Type of contact (phone, email, etc.)', max_length=32)),
                ('value', models.CharField(help_text='Contact value (phone number, email address, etc.)', max_length=256)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this contact is visible in the advertisement')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary contact for the advertisement')),
                ('note', models.CharField(blank=True, help_text='Optional note about this contact', max_length=128)),
                ('car_ad', models.ForeignKey(help_text='Car advertisement this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ads.carad')),
            ],
            options={
                'verbose_name': 'Advertisement Contact',
                'verbose_name_plural': 'Advertisement Contacts',
                'db_table': 'ad_contacts',
                'ordering': ['type', '-is_primary'],
                'indexes': [models.Index(fields=['car_ad', 'is_primary'], name='ad_contact_primary_idx'), models.Index(fields=['car_ad', 'is_visible'], name='ad_contact_visible_idx'), models.Index(fields=['type'], name='ad_contact_type_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('car_ad',), name='unique_primary_contact_per_ad')],
            },
        ),
    ]
