# Generated by Django 5.2.1 on 2025-09-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_create_analytics_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('phone', '📞 Phone'), ('email', '📧 Email'), ('telegram', '📲 Telegram'), ('whatsapp', '💬 WhatsApp'), ('viber', '📡 Viber'), ('instagram', '📸 Instagram'), ('website', '🌐 Website')], help_text='Type of contact (phone, email, etc.)', max_length=32)),
                ('value', models.CharField(help_text='Contact value (phone number, email address, etc.)', max_length=256)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this contact is visible in the advertisement')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary contact for the advertisement')),
                ('note', models.CharField(blank=True, help_text='Optional note about this contact', max_length=128)),
                ('car_ad', models.ForeignKey(help_text='Car advertisement this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ads.carad')),
            ],
            options={
                'verbose_name': 'Advertisement Contact',
                'verbose_name_plural': 'Advertisement Contacts',
                'db_table': 'ad_contacts',
                'ordering': ['type', '-is_primary'],
            },
        ),
        migrations.AddIndex(
            model_name='adcontact',
            index=models.Index(fields=['car_ad', 'is_primary'], name='ad_contact_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='adcontact',
            index=models.Index(fields=['car_ad', 'is_visible'], name='ad_contact_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='adcontact',
            index=models.Index(fields=['type'], name='ad_contact_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='adcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('car_ad',), name='unique_primary_contact_per_ad'),
        ),
    ]
