# Generated by Django 5.2.1 on 2025-09-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_create_analytics_models'),
        ('ads', '0009_add_ad_contact_only'),
    ]

    operations = [
    ]
