# Generated by Django 5.2.1 on 2025-09-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_merge_20250901_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional contact information for this ad', null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Contact person name for this ad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='use_profile_contacts',
            field=models.BooleanField(default=False, help_text='Use contacts from user profile instead of ad-specific contacts'),
        ),
    ]
