# Generated by Django 5.2.4 on 2025-09-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_add_metallic_pearlescent_to_colors"),
        ("ads", "0011_add_contact_strategy_fields"),
    ]

    operations = []
