# Generated by Django 5.2.1 on 2025-09-11 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_change_address_to_onetoone'),
        ('ads', '0012_merge_20250911_0028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('favorited_at', models.DateTimeField(auto_now_add=True, help_text='When this ad was added to favorites')),
            ],
            options={
                'verbose_name': 'Favorite Ad',
                'verbose_name_plural': 'Favorite Ads',
                'db_table': 'ads_favorite_ads',
            },
        ),
        migrations.RemoveConstraint(
            model_name='carmarkmodel',
            name='unique_car_mark_name',
        ),
        migrations.AddField(
            model_name='adinteraction',
            name='owner_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='carad',
            index=models.Index(fields=['status', 'created_at'], name='car_ads_status_66437e_idx'),
        ),
        migrations.AddIndex(
            model_name='carad',
            index=models.Index(fields=['account', 'status'], name='car_ads_account_c12faf_idx'),
        ),
        migrations.AddIndex(
            model_name='carad',
            index=models.Index(fields=['mark', 'status'], name='car_ads_mark_id_7ead6e_idx'),
        ),
        migrations.AddIndex(
            model_name='carad',
            index=models.Index(fields=['price', 'currency'], name='car_ads_price_381e03_idx'),
        ),
        migrations.AddIndex(
            model_name='carad',
            index=models.Index(fields=['region', 'city'], name='car_ads_region__7f0af8_idx'),
        ),
        migrations.AddField(
            model_name='favoritead',
            name='car_ad',
            field=models.ForeignKey(help_text='The car ad that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ads.carad'),
        ),
        migrations.AddField(
            model_name='favoritead',
            name='user',
            field=models.ForeignKey(help_text='User who favorited this ad', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favoritead',
            index=models.Index(fields=['user', 'favorited_at'], name='ads_favorit_user_id_649fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritead',
            index=models.Index(fields=['car_ad', 'favorited_at'], name='ads_favorit_car_ad__12a880_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritead',
            unique_together={('user', 'car_ad')},
        ),
    ]
