# Generated by Django 5.2.1 on 2025-10-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_remove_unique_car_mark_constraint_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('sold', 'Sold'), ('archived', 'Archived')], default='active', help_text='Current status of the advertisement', max_length=20),
        ),
    ]
