/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-translation-types.js
 * Generated at: 2025-11-07T14:32:24.867Z
 */

/**
 * Строго типізований інтерфейс для всіх ключів перекладів
 * Забезпечує type-safety на рівні компіляції
 */
export interface TranslationKeys {
,: string;
-: string;
/: string;
/api/auth/logout: string;
/autoria/create-ad: string;
/autoria/search?favorites_only=true: string;
/error: string;
/login: string;
=: string;
@/components/Forms/RegistrationForm/RegistrationForm: string;
@/services/serviceRegistry: string;
Ad Preview: string;
Ad Title Placeholder: string;
Contact Information: string;
Content-Type: string;
Currency Not Selected: string;
Description: string;
Description Not Added: string;
Fill Required Fields: string;
Fuel: string;
Language: string;
Mileage: string;
Name Not Specified: string;
Phone Not Specified: string;
Preview: string;
Price Not Specified: string;
Review Data Before Publishing: string;
Transmission: string;
Year: string;
\n: string;
a: string;
adStatistics: string;
ad_id: string;
addContact: string;
additionalInfo: string;
additionalInfoPlaceholder: string;
ai: {
  pleaseGoToTabs: string;
  requiredFieldsTitle: string;
  requiredFieldsDescription: string;
};
alert: string;
allDrive: string;
allTime: string;
auth_token: string;
autoFill: {
  additionalPhone: string;
  city: string;
  email: string;
  mainPhone: string;
  region: string;
  sellerName: string;
  telegram: string;
  viber: string;
  whatsapp: string;
};
autoria: {
  activeAds: string;
  adApproved: string;
  adRejected: string;
  adminLabel: string;
  analytics: string;
  analyticsDesc: string;
  applySuggestions: string;
  approved: string;
  autoModerationDesc: string;
  autoSave: string;
  back: string;
  basicInfo: string;
  basicInfoDesc: string;
  basicInfoTitle: string;
  beingChecked: string;
  benefits: {
    effective: {
      description: string;
      title: string;
    };
    fast: {
      description: string;
      title: string;
    };
    security: {
      description: string;
      title: string;
    };
  };
  brand: string;
  byViews: string;
  carSpecsDescription: string;
  carSpecsTitle: string;
  changeSearchParams: string;
  characters: string;
  condition: string;
  contactDesc: string;
  contactTitle: string;
  continue: string;
  createAd: string;
  createAdDesc: string;
  createAdTitle: string;
  createFirstAd: string;
  currentRates: string;
  description: string;
  descriptionCounter: string;
  favorites: string;
  fixFollowingErrors: string;
  formFieldErrors: string;
  hide: string;
  images: string;
  imagesDesc: string;
  inFavorites: string;
  loading: string;
  loadingAds: string;
  locationDesc: string;
  locationTitle: string;
  manualReviewDesc: string;
  metadataDescription: string;
  metadataTitle: string;
  model: string;
  moderation: {
    accessDenied: string;
    active: string;
    allStatuses: string;
    approve: string;
    createdAt: string;
    description: string;
    needsReview: string;
    noAdsDescription: string;
    noAdsFound: string;
    pendingModeration: string;
    reject: string;
    rejected: string;
    review: string;
    searchPlaceholder: string;
    todayModerated: string;
    totalAds: string;
    viewDetails: string;
    status: {
      draft: string;
      pending: string;
      needsReview: string;
      active: string;
      rejected: string;
      blocked: string;
      sold: string;
      archived: string;
    };
    activate: string;
    bulkDone: string;
    confirmBulkDelete: string;
    bulkDeleted: string;
    deleteFailed: string;
    statusUpdated: string;
    statusUpdateFailed: string;
    confirmDelete: string;
    adDeleted: string;
    notesSaved: string;
    notesSaveError: string;
    userStatus: string;
    superuser: string;
    authLoading: string;
    userProfile: string;
    block: string;
    filters: string;
    refresh: string;
    sortBy: string;
    price: string;
    brand: string;
    year: string;
    view: string;
    loadingModeration: string;
    model: string;
    user: string;
    created: string;
    actions: string;
    selected: string;
    rejectionReasonPrompt: string;
    blockReason: string;
    adDetails: string;
    basicInfo: string;
    location: string;
    contactInfo: string;
    phone: string;
    technicalSpecs: string;
    mileage: string;
    fuelType: string;
    transmission: string;
    bodyType: string;
    images: string;
    moderationNotes: string;
    editNotes: string;
    addNotes: string;
    notesPlaceholder: string;
    saveNotes: string;
  };
  moderationInProgress: string;
  moderationInfo: string;
  myAds: string;
  needToFill: string;
  needsManualReview: string;
  newest: string;
  noAdsFound: string;
  noAdsYet: string;
  of: string;
  oldest: string;
  premium: string;
  premiumUsers: string;
  preview: string;
  priceDesc: string;
  priceHigh: string;
  priceLow: string;
  priceTitle: string;
  profile: string;
  profileDesc: string;
  progressFill: string;
  quickSearch: string;
  readyToPublish: string;
  recommendations: string;
  rejected: string;
  requiredSections: string;
  retry: string;
  saveChanges: string;
  saving: string;
  searchCars: string;
  searchCarsDesc: string;
  searchPlaceholder: string;
  selectCondition: string;
  selectVehicleType: string;
  sortBy: string;
  statusFilter: string;
  subtitle: string;
  tabs: {
    contact: string;
    contactDesc: string;
    images: string;
    location: string;
    locationDesc: string;
    pricing: string;
    pricingDesc: string;
    specs: string;
    specsDesc: string;
    statistics: string;
    statisticsDesc: string;
  };
  testAds: {
    clearAll: string;
    creating: string;
    creatingDemo: string;
    errorDeleting: string;
    existingAds: {
      addImages: string;
      noOptions: string;
      options: string;
      processing: string;
      removeEmpty: string;
      rewriteRecords: string;
      title: string;
    };
    generatorButton: string;
    generatorButtonShort: string;
    imageTypes: {
      front: string;
      generate: string;
      interior: string;
      noSelection: string;
      rear: string;
      selectAll: string;
      side: string;
      title: string;
      top: string;
    };
    manageAccounts: string;
    allTestAds: string;
    successCreatedTitle: string;
  };
  tip1: string;
  tip2: string;
  tip3: string;
  tip4: string;
  title: string;
  titleCounter: string;
  totalAds: string;
  totalUsers: string;
  underReview: string;
  updated: string;
  validationErrors: string;
  violations: string;
  whyChoose: string;
  dataSource: {
    cache: string;
    fresh: string;
    mockFallback: string;
    errorFallback: string;
    error: string;
  };
  platformStats: string;
  thisAd: string;
  searchAutoApplyNotice: string;
  new: string;
  used: string;
  withPhotos: string;
  verified: string;
  byDate: string;
  byPrice: string;
  byYear: string;
  byMileage: string;
  byTitle: string;
  perPage: string;
  all: string;
  view: string;
  tryAdjustFilters: string;
  prev: string;
  next: string;
  mainImage: string;
  noImages: string;
  locationDescription: string;
  basicInfoDescription: string;
  fileNotImage: string;
  fileTooLarge: string;
  max10MB: string;
  fillRequiredFieldsForGeneration: string;
  allImages: string;
  editAd: string;
  completeness: string;
  additional: {
    settings: {
      title: string;
      status: string;
      active: string;
      draft: string;
      paused: string;
      tags: {
        add: string;
      };
      internalNotes: string;
      internalNotesPlaceholder: string;
    };
    metadata: {
      title: string;
      seoTitle: string;
      seoTitlePlaceholder: string;
    };
    privacy: {
      showPublic: string;
      phoneTitle: string;
      phoneDesc: string;
      exactAddressTitle: string;
      exactAddressDesc: string;
      ownerNameTitle: string;
      ownerNameDesc: string;
    };
  };
  editAdTitle: string;
  deleteAdTitle: string;
  editAdDesc: string;
  deleteAdDesc: string;
  confirmDelete: string;
  confirmDeleteDesc: string;
  ad: string;
  form: {
    tabs: {
      basic: {
        label: string;
        description: string;
      };
      images: {
        label: string;
        description: string;
      };
      additional: {
        label: string;
        description: string;
      };
      preview: {
        label: string;
        description: string;
      };
    };
  };
  creating: string;
  completed: string;
  additionalInfo: string;
  noTitle: string;
  noDescription: string;
  pricingDesc: string;
};
backend_auth: string;
basic: string;
basicInfo: {
  demoTab: string;
  formTab: string;
  fillTitleDescription: string;
  validationError: string;
};
bg: string;
bodyType: string;
brand: string;
callbackUrl: string;
chartsAndTrends: string;
city: string;
clear-file-upload-notification: string;
color: string;
common: {
  actions: string;
  anyRegion: string;
  cancel: string;
  continue: string;
  delete: string;
  edit: string;
  error: string;
  loading: string;
  none: string;
  open: string;
  preview: string;
  refresh: string;
  save: string;
  search: string;
  searchPlaceholder: string;
  select: string;
  selectOption: string;
  success: string;
  validation: {
    brand: {
      required: string;
    };
    description: {
      maxLength: string;
      minLength: string;
      required: string;
    };
    error: string;
    mileage: {
      invalid: string;
      max: string;
      min: string;
      required: string;
    };
    model: {
      required: string;
    };
    requiredFields: string;
    title: {
      maxLength: string;
      minLength: string;
      required: string;
    };
    vehicleType: {
      required: string;
    };
    year: {
      invalid: string;
      max: string;
      min: string;
      required: string;
    };
  };
  ok: string;
  updated: string;
  clear: string;
  invert: string;
  found: string;
  sort: string;
  warning: string;
  saving: string;
  deleting: string;
  creating: string;
  create: string;
  reset: string;
};
companySeller: string;
condition: string;
contactNotePlaceholder: string;
contactTip: string;
contactType: string;
contactValue: string;
content-type: string;
contentValidationModal: {
  acceptAndContinue: string;
  censoredContent: string;
  close: string;
  confidence: string;
  contentRejected: string;
  fixAndRetry: string;
  inappropriateWords: string;
  originalContent: string;
  statusValidation: string;
  suggestions: string;
  title: string;
  violations: string;
};
continue: string;
created_desc: string;
currency: string;
currencyDescription: string;
dark-mode-changed: string;
date-changed: string;
dealerSeller: string;
delete: string;
description: string;
descriptionDescription: string;
detailedAnalytics: string;
detailedStatistics: string;
doors: string;
doorsDescription: string;
driveType: string;
driveTypeDescription: string;
edit: string;
email: string;
enginePower: string;
enginePowerDescription: string;
engineVolume: string;
enterDescription: string;
enterLicensePlate: string;
enterMileage: string;
enterPower: string;
enterPrice: string;
enterSeats: string;
enterTitle: string;
enterVin: string;
enterVolume: string;
enterYear: string;
error: string;
eur: string;
exchange: string;
exchangePossible: string;
exchangeStatus: string;
exchangeStatusDescription: string;
favoritesDesc: string;
favoritesTitle: string;
frontDrive: string;
fuelType: string;
highlightAd: string;
highlightAdDescription: string;
instagram: string;
interactiveEditor: {
  adDescription: string;
  adTitle: string;
  close: string;
  descriptionCharacters: string;
  descriptionPlaceholder: string;
  resetToOriginal: string;
  runValidation: string;
  title: string;
  titleCharacters: string;
  titlePlaceholder: string;
  validating: string;
};
key: string;
last30Days: string;
last7Days: string;
leftSteering: string;
licensePlate: string;
licensePlateDescription: string;
limit: string;
link: string;
loading: string;
lowViewsToday: string;
message: string;
mileage: string;
model: string;
moderation: {
  userBlocked: string;
  errorBlocking: string;
  userUnblocked: string;
  errorUnblocking: string;
  savedSuccessfully: string;
  errorSaving: string;
};
myAdsDesc: string;
myAdsTitle: string;
navigation: {
  analytics: string;
  home: string;
  language: string;
  myAds: string;
  profile: string;
  search: string;
  createAd: string;
  favorites: string;
  moderation: string;
};
next: string;
noExchange: string;
numberOfDoors: string;
numberOfSeats: string;
onlyExchange: string;
optionalNote: string;
page: string;
page_size: string;
password: string;
phone: string;
premium: string;
premiumBenefits: string;
price: string;
priceAboveRegionAverage: string;
priceAnalysis: string;
priceDescription: string;
price_from: string;
priorityPlacement: string;
privateSeller: string;
profile: {
  account: {
    accountId: string;
    adminOnlyFields: string;
    created: string;
    enableStats: string;
    moderationLevel: string;
    noAccount: string;
    orgPlaceholder: string;
    organizationName: string;
    role: string;
    save: string;
    saving: string;
    selectAccountType: string;
    selectModerationLevel: string;
    selectRole: string;
    status: string;
    type: string;
    updateError: string;
    updateSuccess: string;
  };
  accountSettings: string;
  accountTypes: {
    basic: string;
    business: string;
    premium: string;
  };
  address: {
    aboutRaw: string;
    aboutRawDesc: {
      coordinates: string;
      geocoding: string;
      placeId: string;
    };
    add: string;
    addAddressDescription: string;
    addressComponents: string;
    addressDetails: string;
    addressHash: string;
    addresses: string;
    autoGenerated: string;
    autoRefresh: string;
    cancel: string;
    coordinates: string;
    delete: string;
    edit: string;
    formattedAddress: string;
    geocoded: string;
    geocoding: string;
    geocodingError: string;
    googlePlaceId: string;
    helpText: {
      autoGeocode: string;
      selectRegion: string;
    };
    hideMap: string;
    input: string;
    latin: string;
    liveSync: string;
    locality: string;
    localityPlaceholder: string;
    location: string;
    noAddress: string;
    noCitiesFound: string;
    noRegionsFound: string;
    openInGoogleMaps: string;
    pending: string;
    pendingGeocoding: string;
    placeId: string;
    region: string;
    regionPlaceholder: string;
    save: string;
    searchCity: string;
    searchRegion: string;
    selectRegionFirst: string;
    showMap: string;
    standardized: string;
    standardizedData: string;
    standardizedLocality: string;
    standardizedRegion: string;
    syncing: string;
    ukrainian: string;
    updateSuccess: string;
    userInput: string;
    verified: string;
    yourAddress: string;
    thisAddress: string;
    primary: string;
    noAddresses: string;
  };
  addresses: string;
  avatar: {
    cancel: string;
    customPlaceholder: string;
    customRequirements: string;
    failed: string;
    fileInfo: string;
    gender: string;
    genders: {
      female: string;
      male: string;
      neutral: string;
    };
    generate: string;
    generate_button: string;
    generating: string;
    saveWarning: string;
    selectGender: string;
    selectStyle: string;
    style: string;
    styles: {
      anime: string;
      artistic: string;
      caricature: string;
      cartoon: string;
      professional: string;
      realistic: string;
    };
    success: string;
    title: string;
    upload: string;
  };
  contact: {
    add: string;
    addFirst: string;
    email: string;
    list: string;
    noContacts: string;
    phone: string;
    primary: string;
    selectType: string;
    telegram: string;
    type: string;
    value: string;
    valuePlaceholder: string;
    verified: string;
    viber: string;
    whatsapp: string;
    edit: string;
    update: string;
    thisContact: string;
    deleteSuccess: string;
    deleteError: string;
  };
  contacts: string;
  form: {
    age: string;
    agePlaceholder: string;
    email: string;
    emailNote: string;
    firstName: string;
    firstNamePlaceholder: string;
    lastName: string;
    lastNamePlaceholder: string;
    save: string;
    saving: string;
    updateError: string;
    updateSuccess: string;
  };
  moderationLevels: {
    auto: string;
    manual: string;
    strict: string;
  };
  personalInfo: string;
  roles: {
    buyer: string;
    dealer: string;
    seller: string;
  };
  saving: string;
  title: string;
};
rearDrive: string;
recommendations: string;
region: string;
regionAverage: string;
region_id: string;
required: string;
returnUrl: string;
rightSteering: string;
scroll-chat-to-bottom: string;
search: string;
searchDesc: string;
searchTitle: string;
seatsDescription: string;
seed: string;
selectBodyType: string;
selectBrand: string;
selectBrandFirst: string;
selectCity: string;
selectColor: string;
selectCondition: string;
selectCurrency: string;
selectDoors: string;
selectDriveType: string;
selectExchangeStatus: string;
selectFuelType: string;
selectModel: string;
selectRegion: string;
selectRegionFirst: string;
selectSellerType: string;
selectSteeringWheel: string;
selectTransmission: string;
selectVehicleType: string;
selectVehicleTypeFirst: string;
sellerType: string;
sellerTypeDescription: string;
session_token: string;
skip: string;
statisticsAfterPublication: string;
statisticsUnavailable: string;
statisticsUnavailableDesc: string;
steeringWheel: string;
steeringWheelDescription: string;
telegram: string;
text: string;
thisMonth: string;
thisWeek: string;
tip: string;
title: string;
titleDescription: string;
today: string;
totalViews: string;
transmission: string;
tryUpdatePhotosOrDescription: string;
uah: string;
uk-UA: string;
ukraineAverage: string;
unlimitedAds: string;
upgradeToPremium: string;
urgentSale: string;
urgentSaleDescription: string;
usd: string;
validating: string;
validation: {
  attemptsLeft: string;
  autoModeration: string;
  checkNow: string;
  checkPlatformCompliance: string;
  checkProfanity: string;
  checkSuspiciousContent: string;
  yourAdWillBeChecked: string;
  passwordsDoNotMatch: string;
  email: {
    required: string;
    invalid: string;
  };
  password: {
    required: string;
    minLength: string;
  };
  confirmPassword: {
    required: string;
    mustMatch: string;
  };
};
validationDemo: {
  buttons: {
    editAndValidate: string;
    quickValidation: string;
  };
  scenarios: {
    correctAd: {
      description: string;
      title: string;
    };
    nonAutomotive: {
      description: string;
      title: string;
    };
    profanityRussian: {
      description: string;
      title: string;
    };
    profanityTranslit: {
      description: string;
      title: string;
    };
    spamAdvertising: {
      description: string;
      title: string;
    };
  };
  status: {
    approved: string;
    needsReview: string;
    rejected: string;
  };
  subtitle: string;
  title: string;
};
vehicleType: string;
viber: string;
viewsToday: string;
vinCode: string;
vinDescription: string;
website: string;
whatsapp: string;
year: string;
year_from: string;
yourPosition: string;
yourPrice: string;
yourPriceDesc: string;
profile.avatar.failed: string;
profile.avatar.saveWarning: string;
: {
  : string;
};
toast: {
  success: string;
  error: string;
  warning: string;
  info: string;
};
authRequired: {
  title: string;
  description: string;
  autoRedirect: string;
  loginButton: string;
};
searchRegion: string;
nothingFound: string;
noRegions: string;
searchCity: string;
Home: string;
Login: string;
Auth: string;
accessDenied: {
  moderatorRequired: string;
  superuserRequired: string;
  moderationTitle: string;
  moderationDescription: string;
};
searchFilters: string;
enterBrandModel: string;
searchAutoApplyNotice: string;
searchResults: string;
notifications: {
  moderationApproved: string;
  moderationRejected: string;
  moderationReviewSent: string;
  moderationBlocked: string;
  moderationActivated: string;
  success: string;
  error: string;
  moderationActionError: string;
  loginRequiredForFavorites: string;
  favoriteAddError: string;
  tryAgain: string;
  phoneShown: string;
  phoneNumber: string;
};
auth: {
  loginRequiredTitle: string;
  loginRequiredDesc: string;
  loggingOut: string;
  tokensClearedPleaseLogin: string;
  failedToClearTokens: string;
};
adView: {
  backButton: string;
  description: string;
  characteristics: string;
  type: string;
  brand: string;
  model: string;
  year: string;
  mileage: string;
  fuelType: string;
  transmission: string;
  location: string;
  contactInfo: string;
  showPhone: string;
  sendEmail: string;
};
myAds: {
  deleteError: string;
};
enterEngineVolume: string;
enterEnginePower: string;
enterVinCode: string;
contactsSaved: string;
contactsSavedDescription: string;
saveContacts: string;
fuelTypes: {
  petrol: string;
  diesel: string;
  gas: string;
  hybrid: string;
  electric: string;
};
transmissions: {
  manual: string;
  automatic: string;
  robot: string;
  cvt: string;
};
bodyTypes: {
  sedan: string;
  hatchback: string;
  wagon: string;
  suv: string;
  coupe: string;
  convertible: string;
  pickup: string;
  van: string;
  minivan: string;
};
conditions: {
  new: string;
  used: string;
  damaged: string;
};
premiumFeature: {
  title: string;
  description: string;
  upgradeButton: string;
  contactAdmin: string;
};
includeImages: string;
imageTypes: string;
userSelector: {
  loading: string;
  error: string;
  placeholder: string;
};
address: {
  geocodingInProgress: string;
  loadingDetails: string;
  howItWorks: string;
};
form: {
  quickGenerate: string;
  clearForm: string;
  quickPreview: string;
  generateTestData: string;
  clearAllForm: string;
};
login: {
  title: string;
  register: string;
  selectProviderPlaceholder: string;
  dummyForm: {
    username: string;
    password: string;
    duration: string;
    durationPlaceholder: string;
    options: {
      minutes30: string;
      minutes60: string;
    };
  };
  backendForm: {
    email: string;
    password: string;
  };
  toast: {
    authTitle: string;
    validationTitle: string;
    validationDescription: string;
  };
};
registration: {
  title: string;
  login: string;
  fields: {
    email: string;
    password: string;
    confirmPassword: string;
  };
  button: {
    register: string;
    reset: string;
  };
};
}

/**
 * Тип для мови
 */
export type Language = 'en' | 'ru' | 'uk';

/**
 * Тип для отримання значення перекладу за ключем
 */
export type TranslationValue<K extends keyof TranslationKeys> = string;

/**
 * Хелпер тип для глибокого доступу до ключів
 */
export type DeepKeys<T> = T extends object
  ? {
      [K in keyof T]: K extends string
        ? T[K] extends object
          ? `${K}.${DeepKeys<T[K]>}` | K
          : K
        : never;
    }[keyof T]
  : never;

/**
 * Всі можливі ключі перекладів (включно з вкладеними)
 */
export type TranslationKey = DeepKeys<TranslationKeys>;

/**
 * Метадані перекладів
 */
export interface TranslationMeta {
  version: string;
  lastUpdated: string;
  totalKeys: number;
  languages: Language[];
}

/**
 * Повна структура перекладів
 */
export interface TranslationsStructure {
  meta: TranslationMeta;
  translations: TranslationKeys;
}
