# Generated by Django 5.2.4 on 2025-10-19 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial Success"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("NBU", "National Bank of Ukraine"),
                            ("PRIVATBANK", "PrivatBank API"),
                            ("EXCHANGERATE_API", "ExchangeRate-API"),
                            ("FIXER_IO", "Fixer.io"),
                            ("MANUAL", "Manual Entry"),
                        ],
                        help_text="Источник обновления",
                        max_length=20,
                    ),
                ),
                ("currencies_updated", models.PositiveIntegerField(default=0)),
                ("currencies_failed", models.PositiveIntegerField(default=0)),
                (
                    "success_details",
                    models.JSONField(
                        blank=True, help_text="Детали успешных обновлений", null=True
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(blank=True, help_text="Детали ошибок", null=True),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="celery_beat",
                        help_text="Кто/что запустило обновление",
                        max_length=50,
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Длительность обновления в секундах",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Currency Update Log",
                "verbose_name_plural": "Currency Update Logs",
                "db_table": "currency_update_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("UAH", "Ukrainian Hryvnia"),
                            ("PLN", "Polish Zloty"),
                            ("GBP", "British Pound"),
                        ],
                        default="UAH",
                        help_text="Базовая валюта (к которой приводятся курсы)",
                        max_length=3,
                    ),
                ),
                (
                    "target_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("UAH", "Ukrainian Hryvnia"),
                            ("PLN", "Polish Zloty"),
                            ("GBP", "British Pound"),
                        ],
                        help_text="Целевая валюта",
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Курс валюты (сколько базовой валюты за 1 единицу целевой)",
                        max_digits=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("NBU", "National Bank of Ukraine"),
                            ("PRIVATBANK", "PrivatBank API"),
                            ("EXCHANGERATE_API", "ExchangeRate-API"),
                            ("FIXER_IO", "Fixer.io"),
                            ("MANUAL", "Manual Entry"),
                        ],
                        default="NBU",
                        help_text="Источник курса",
                        max_length=20,
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Время получения курса",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Активен ли курс"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Сырые данные от API", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency Rate",
                "verbose_name_plural": "Currency Rates",
                "db_table": "currency_rates",
                "ordering": ["-fetched_at", "target_currency"],
                "indexes": [
                    models.Index(
                        fields=["base_currency", "target_currency", "-fetched_at"],
                        name="currency_ra_base_cu_c51eb0_idx",
                    ),
                    models.Index(
                        fields=["source", "-fetched_at"],
                        name="currency_ra_source_cb5676_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-fetched_at"],
                        name="currency_ra_is_acti_f77109_idx",
                    ),
                ],
                "unique_together": {("base_currency", "target_currency", "fetched_at")},
            },
        ),
    ]
