# Generated by Django 5.2.1 on 2025-07-26 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account_type', models.CharField(choices=[('BASIC', 'Basic account'), ('PREMIUM', 'Premium account')], default='BASIC', max_length=16)),
                ('moderation_level', models.CharField(choices=[('LIGHT', 'Light moderation'), ('STRICT', 'Strict moderation'), ('AUTO', 'Automated check only')], max_length=64)),
                ('role', models.CharField(choices=[('seller', 'Private seller'), ('dealer', 'Car dealership'), ('manager', 'Dealership manager')], default='seller', max_length=32)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('stats_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_adds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'add_accounts',
            },
        ),
        migrations.CreateModel(
            name='AddsAccountContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('phone', '📞 Phone'), ('email', '📧 Email'), ('telegram', '📲 Telegram'), ('whatsapp', '💬 WhatsApp'), ('viber', '📡 Viber'), ('instagram', '📸 Instagram'), ('website', '🌐 Website')], max_length=32)),
                ('value', models.CharField(max_length=256)),
                ('is_visible', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('adds_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.addsaccount')),
            ],
            options={
                'db_table': 'add_account_contacts',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='RawAccountAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.CharField(default='Україна', max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('district', models.CharField(blank=True, max_length=128)),
                ('locality', models.CharField(blank=True, max_length=128)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('building', models.CharField(blank=True, max_length=32)),
                ('apartment', models.CharField(blank=True, max_length=16)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_addresses', to='accounts.addsaccount')),
            ],
            options={
                'db_table': 'raw_account_addresses',
            },
        ),
        migrations.CreateModel(
            name='FormattedAccountAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('formatted_address', models.TextField()),
                ('geocode', models.CharField(blank=True, max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street_number', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('sublocality', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('administrative_area_level_1', models.CharField(blank=True, max_length=255)),
                ('administrative_area_level_2', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('raw_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formatted_address', to='accounts.rawaccountaddress')),
            ],
            options={
                'db_table': 'formatted_account_addresses',
            },
        ),
    ]
