# Generated by Django 5.2.4 on 2025-10-09 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="addsaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_adds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="addsaccountcontact",
            name="adds_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="accounts.addsaccount",
            ),
        ),
        migrations.AddField(
            model_name="dealershipemployee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealership_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dealershiporganization",
            name="owner",
            field=models.ForeignKey(
                help_text="Владелец автосалона",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_dealerships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dealershipemployee",
            name="dealership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="accounts.dealershiporganization",
            ),
        ),
        migrations.AddField(
            model_name="addsaccount",
            name="dealership",
            field=models.ForeignKey(
                blank=True,
                help_text="Автосалон, к которому принадлежит аккаунт",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="accounts.dealershiporganization",
            ),
        ),
        migrations.AddField(
            model_name="rawaccountaddress",
            name="account",
            field=models.OneToOneField(
                help_text="One address per account - unique constraint",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="accounts.addsaccount",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dealershipemployee",
            unique_together={("dealership", "user")},
        ),
        migrations.AddIndex(
            model_name="rawaccountaddress",
            index=models.Index(fields=["geo_code"], name="raw_addr_geo_code_idx"),
        ),
        migrations.AddIndex(
            model_name="rawaccountaddress",
            index=models.Index(
                fields=["region", "locality"], name="raw_addr_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawaccountaddress",
            index=models.Index(fields=["is_geocoded"], name="raw_addr_geocoded_idx"),
        ),
        migrations.AddConstraint(
            model_name="rawaccountaddress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("geo_code__isnull", False),
                    models.Q(("geo_code", ""), _negated=True),
                ),
                name="geo_code_required",
            ),
        ),
    ]
