# Generated by Django 5.2.1 on 2025-07-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsaccount',
            name='moderation_level',
            field=models.CharField(choices=[('LIGHT', 'Light moderation'), ('STRICT', 'Strict moderation'), ('AUTO', 'Automated check only')], default='AUTO', max_length=64),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='formatted_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
