# Generated by Django 5.2.4 on 2025-07-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_addsaccount_moderation_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addsaccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("seller", "Продавець (звичайний користувач)"),
                    ("dealer", "Автосалон"),
                    ("manager", "Менеджер платформи (staff)"),
                    ("admin", "Адміністратор (superuser)"),
                ],
                default="seller",
                max_length=32,
            ),
        ),
    ]
