# Generated by Django 5.2.1 on 2025-07-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_improve_formatted_address_fields'),
        ('accounts', '0003_alter_addsaccount_role'),
    ]

    operations = [
    ]
