# Generated by Django 5.2.1 on 2025-07-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20250731_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='address_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of standardized address components for grouping', max_length=64),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='apartment',
            field=models.CharField(blank=True, help_text='Apartment number (copied from raw address)', max_length=50),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='country',
            field=models.CharField(blank=True, help_text='Country name in Latin (standardized by Google Maps)', max_length=255),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO country code (e.g., UA for Ukraine)', max_length=8),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='district',
            field=models.CharField(blank=True, help_text='District in Latin (standardized by Google Maps)', max_length=255),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='formatted_address',
            field=models.TextField(blank=True, help_text='Complete formatted address from Google Maps API'),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='locality',
            field=models.CharField(blank=True, help_text='City/Village in Latin (standardized by Google Maps)', max_length=255),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='place_id',
            field=models.CharField(help_text='Unique Google Maps place identifier', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code (standardized by Google Maps)', max_length=50),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='region',
            field=models.CharField(blank=True, help_text='Region/Oblast in Latin (standardized by Google Maps)', max_length=255),
        ),
        migrations.AlterField(
            model_name='formattedaccountaddress',
            name='street',
            field=models.CharField(blank=True, help_text='Street name in Latin (standardized by Google Maps)', max_length=255),
        ),
    ]
