# Generated by Django 5.2.1 on 2025-07-30 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_formatted_address_structure'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='formattedaccountaddress',
            name='formatted_addr_place_id_idx',
        ),
        migrations.RemoveField(
            model_name='formattedaccountaddress',
            name='administrative_area_level_1',
        ),
        migrations.RemoveField(
            model_name='formattedaccountaddress',
            name='administrative_area_level_2',
        ),
        migrations.RemoveField(
            model_name='formattedaccountaddress',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='formattedaccountaddress',
            name='geocode',
        ),
        migrations.RemoveField(
            model_name='formattedaccountaddress',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='formattedaccountaddress',
            name='route',
        ),
        migrations.RemoveField(
            model_name='formattedaccountaddress',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='formattedaccountaddress',
            name='sublocality',
        ),
    ]
