# Generated by Django 5.2.1 on 2025-07-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_optimize_address_structure'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawaccountaddress',
            name='raw_addr_hash_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawaccountaddress',
            name='raw_addr_location_idx',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='address_hash',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='building',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='original_apartment',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='original_building',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='original_country',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='original_district',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='original_locality',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='original_postal_code',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='original_region',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='original_street',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='rawaccountaddress',
            name='street',
        ),
        migrations.AddField(
            model_name='rawaccountaddress',
            name='geo_code',
            field=models.CharField(db_index=True, default='unknown_location', help_text='Unique geographical code: region + locality for grouping ads', max_length=128),
        ),
        migrations.AddField(
            model_name='rawaccountaddress',
            name='input_locality',
            field=models.CharField(default='', help_text='City/locality as entered by user (required for geocoding)', max_length=255),
        ),
        migrations.AddField(
            model_name='rawaccountaddress',
            name='input_region',
            field=models.CharField(default='', help_text='Region as entered by user (required for geocoding)', max_length=255),
        ),
        migrations.AlterField(
            model_name='rawaccountaddress',
            name='is_geocoded',
            field=models.BooleanField(default=False, help_text='Whether geocoding was successful'),
        ),
        migrations.AlterField(
            model_name='rawaccountaddress',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for map display', null=True),
        ),
        migrations.AlterField(
            model_name='rawaccountaddress',
            name='locality',
            field=models.CharField(blank=True, db_index=True, help_text='Standardized locality name (Google Maps, locale: uk)', max_length=255),
        ),
        migrations.AlterField(
            model_name='rawaccountaddress',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for map display', null=True),
        ),
        migrations.AlterField(
            model_name='rawaccountaddress',
            name='region',
            field=models.CharField(blank=True, db_index=True, help_text='Standardized region name (Google Maps, locale: uk)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='rawaccountaddress',
            index=models.Index(fields=['geo_code'], name='raw_addr_geo_code_idx'),
        ),
        migrations.AddIndex(
            model_name='rawaccountaddress',
            index=models.Index(fields=['region', 'locality'], name='raw_addr_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawaccountaddress',
            constraint=models.CheckConstraint(condition=models.Q(('geo_code__isnull', False), models.Q(('geo_code', ''), _negated=True)), name='geo_code_required'),
        ),
    ]
