# Generated by Django 5.2.1 on 2025-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_optimize_for_geographical_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawaccountaddress',
            name='geo_code',
            field=models.CharField(db_index=True, default='unknown', help_text='SHA-256 hash code (8 chars) from standardized region + locality for grouping ads', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='rawaccountaddress',
            constraint=models.CheckConstraint(condition=models.Q(('geo_code__regex', '^[a-f0-9]{8}$'), ('geo_code', 'unknown'), _connector='OR'), name='geo_code_format'),
        ),
    ]
