# Generated by Django 5.2.1 on 2025-07-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_convert_geo_codes_to_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rawaccountaddress',
            name='geo_code_format',
        ),
        migrations.AlterField(
            model_name='rawaccountaddress',
            name='geo_code',
            field=models.CharField(db_index=True, default='unknown', help_text='Google Maps place_id for unique geographical identification and grouping', max_length=128),
        ),
    ]
