# Generated by Django 5.2.1 on 2025-08-02 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_update_geo_code_for_place_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Название автосалона/дилерского центра', max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='Полное юридическое название', max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='Налоговый номер (ЕГРПОУ)', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True, help_text='Физический адрес автосалона')),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Прошел ли автосалон верификацию')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('max_ads', models.PositiveIntegerField(default=100, help_text='Максимальное количество активных объявлений')),
                ('owner', models.ForeignKey(help_text='Владелец автосалона', on_delete=django.db.models.deletion.CASCADE, related_name='owned_dealerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
                'db_table': 'dealership_organizations',
            },
        ),
        migrations.AddField(
            model_name='addsaccount',
            name='dealership',
            field=models.ForeignKey(blank=True, help_text='Автосалон, к которому принадлежит аккаунт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.dealershiporganization'),
        ),
        migrations.CreateModel(
            name='DealershipEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Администратор автосалона'), ('manager', 'Менеджер по продажам'), ('mechanic', 'Механик'), ('sales', 'Продавец')], help_text='Роль сотрудника в автосалоне', max_length=20)),
                ('can_create_ads', models.BooleanField(default=True)),
                ('can_edit_ads', models.BooleanField(default=True)),
                ('can_delete_ads', models.BooleanField(default=False)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hired_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_roles', to=settings.AUTH_USER_MODEL)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.dealershiporganization')),
            ],
            options={
                'verbose_name': 'Сотрудник автосалона',
                'verbose_name_plural': 'Сотрудники автосалонов',
                'db_table': 'dealership_employees',
                'unique_together': {('dealership', 'user')},
            },
        ),
    ]
