# Generated by Django 5.2.1 on 2025-08-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_dealershiporganization_addsaccount_dealership_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawaccountaddress',
            options={'verbose_name': 'Account Address', 'verbose_name_plural': 'Account Addresses'},
        ),
        # First, ensure all existing addresses are unique per account
        migrations.RunSQL(
            "DELETE FROM accounts_rawaccountaddress WHERE id NOT IN "
            "(SELECT MIN(id) FROM accounts_rawaccountaddress GROUP BY account_id)",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='rawaccountaddress',
            name='account',
            field=models.OneToOneField(help_text='One address per account - unique constraint', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='accounts.addsaccount'),
        ),
    ]
