#!/bin/bash
# Скрипт для создания frontend/.env.local перед развертыванием
# Читает переменные из env-config/ и создает .env.local для Next.js

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}📝 Создание frontend/.env.local...${NC}"

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
FRONTEND_DIR="$ROOT_DIR/frontend"
ENV_CONFIG_DIR="$ROOT_DIR/env-config"
ENV_LOCAL_PATH="$FRONTEND_DIR/.env.local"

# Create .env.local file
cat > "$ENV_LOCAL_PATH" << 'EOF'
# Auto-generated by setup-frontend-env.sh
# DO NOT COMMIT THIS FILE
# Run 'bash scripts/setup-frontend-env.sh' to regenerate

EOF

# Read and write critical variables from env-config files
FOUND_NEXTAUTH_SECRET=false

for ENV_FILE in "$ENV_CONFIG_DIR/.env.base" "$ENV_CONFIG_DIR/.env.secrets" "$ENV_CONFIG_DIR/.env.local"; do
    if [ -f "$ENV_FILE" ]; then
        echo "   Чтение $(basename "$ENV_FILE")..."
        while IFS='=' read -r key value; do
            # Skip comments and empty lines
            if [[ ! "$key" =~ ^#.* ]] && [ ! -z "$key" ]; then
                case "$key" in
                    NEXTAUTH_SECRET|NEXTAUTH_URL|NEXT_PUBLIC_BACKEND_URL|BACKEND_URL|NODE_ENV|NEXT_PUBLIC_IS_DOCKER|IS_DOCKER|REDIS_HOST|REDIS_URL|GOOGLE_CLIENT_ID|GOOGLE_CLIENT_SECRET|NEXT_PUBLIC_GOOGLE_CLIENT_ID)
                        echo "${key}=${value}" >> "$ENV_LOCAL_PATH"
                        if [ "$key" = "NEXTAUTH_SECRET" ]; then
                            FOUND_NEXTAUTH_SECRET=true
                        fi
                        ;;
                esac
            fi
        done < "$ENV_FILE"
    fi
done

# Add defaults if not present
if ! grep -q "^NODE_ENV=" "$ENV_LOCAL_PATH"; then
    echo "NODE_ENV=production" >> "$ENV_LOCAL_PATH"
fi
if ! grep -q "^NEXTAUTH_URL=" "$ENV_LOCAL_PATH"; then
    echo "NEXTAUTH_URL=http://localhost:3000" >> "$ENV_LOCAL_PATH"
fi
if ! grep -q "^NEXT_PUBLIC_BACKEND_URL=" "$ENV_LOCAL_PATH"; then
    echo "NEXT_PUBLIC_BACKEND_URL=http://localhost:8000" >> "$ENV_LOCAL_PATH"
fi
if ! grep -q "^BACKEND_URL=" "$ENV_LOCAL_PATH"; then
    echo "BACKEND_URL=http://localhost:8000" >> "$ENV_LOCAL_PATH"
fi
if ! grep -q "^NEXT_PUBLIC_IS_DOCKER=" "$ENV_LOCAL_PATH"; then
    echo "NEXT_PUBLIC_IS_DOCKER=false" >> "$ENV_LOCAL_PATH"
fi
if ! grep -q "^IS_DOCKER=" "$ENV_LOCAL_PATH"; then
    echo "IS_DOCKER=false" >> "$ENV_LOCAL_PATH"
fi

echo -e "${GREEN}✅ Створено $ENV_LOCAL_PATH${NC}"

# Check for NEXTAUTH_SECRET
if [ "$FOUND_NEXTAUTH_SECRET" = false ]; then
    echo -e "${YELLOW}⚠️  УВАГА: NEXTAUTH_SECRET не знайдено!${NC}"
    echo "   Переконайтеся що env-config/.env.secrets містить NEXTAUTH_SECRET"
    exit 1
fi

echo "   Готово!"
