#!/usr/bin/env python3
"""
Скрипт для создания frontend/.env.local перед развертыванием
Читает переменные из env-config/ и создает .env.local для Next.js
"""

import os
from pathlib import Path

def create_frontend_env():
    """Создает frontend/.env.local с необходимыми переменными"""
    
    # Пути
    root_dir = Path(__file__).parent.parent
    frontend_dir = root_dir / "frontend"
    env_config_dir = root_dir / "env-config"
    env_local_path = frontend_dir / ".env.local"
    
    print("📝 Создание frontend/.env.local...")
    
    # Читаем переменные из env-config файлов
    env_vars = {}
    env_files = [
        env_config_dir / ".env.base",
        env_config_dir / ".env.secrets",
        env_config_dir / ".env.local",
    ]
    
    for env_file in env_files:
        if env_file.exists():
            print(f"   Чтение {env_file.name}...")
            with open(env_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        # Видаляємо всі переноси рядків та зайві пробіли
                        env_vars[key.strip()] = value.strip().replace('\n', '').replace('\r', '')
    
    # Критичні змінні для Next.js
    critical_vars = [
        'NEXTAUTH_SECRET',
        'NEXTAUTH_URL',
        'NEXT_PUBLIC_BACKEND_URL',
        'BACKEND_URL',
        'NODE_ENV',
        'NEXT_PUBLIC_IS_DOCKER',
        'IS_DOCKER',
        'REDIS_HOST',
        'REDIS_URL',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'NEXT_PUBLIC_GOOGLE_CLIENT_ID'
    ]
    
    # Записуємо в .env.local
    with open(env_local_path, 'w', encoding='utf-8') as f:
        f.write("# Auto-generated by setup-frontend-env.py\n")
        f.write("# DO NOT COMMIT THIS FILE\n")
        f.write("# Run 'python scripts/setup-frontend-env.py' to regenerate\n\n")
        
        for var in critical_vars:
            if var in env_vars:
                f.write(f"{var}={env_vars[var]}\n")
            elif var == 'NODE_ENV':
                f.write(f"{var}=production\n")
            elif var == 'NEXTAUTH_URL':
                f.write(f"{var}=http://localhost:3000\n")
            elif var == 'NEXT_PUBLIC_BACKEND_URL':
                f.write(f"{var}=http://localhost:8000\n")
            elif var == 'BACKEND_URL':
                f.write(f"{var}=http://localhost:8000\n")
            elif var == 'NEXT_PUBLIC_IS_DOCKER':
                f.write(f"{var}=false\n")
            elif var == 'IS_DOCKER':
                f.write(f"{var}=false\n")
    
    print(f"✅ Створено {env_local_path}")
    print(f"   Записано {len(critical_vars)} змінних")
    
    # Перевіряємо наявність NEXTAUTH_SECRET
    if 'NEXTAUTH_SECRET' not in env_vars:
        print("\n⚠️  УВАГА: NEXTAUTH_SECRET не знайдено!")
        print("   Переконайтеся що env-config/.env.secrets містить NEXTAUTH_SECRET")
        return False
    
    return True

if __name__ == "__main__":
    try:
        success = create_frontend_env()
        exit(0 if success else 1)
    except Exception as e:
        print(f"❌ Помилка: {e}")
        exit(1)
